---

# Travis file for locales role

dist: 'xenial'
sudo: 'required'

language: python
python: "2.7"

services:
  - 'docker'

env:
  matrix:
    - TOXENV='py27-ansible24'
    - TOXENV='py27-ansible25'
    - TOXENV='py27-ansible26'
    - TOXENV='py27-ansible27'

install:
  - 'pip install tox-travis'

script:
  - 'tox -e "${TOXENV}"'

notifications:
  webhooks: 'https://galaxy.ansible.com/api/v1/notifications/'
