---

- name     : generate locale configuration file
  template :
    src   : "{{ role_path }}/templates/locale.j2"
    dest  : "{{ locales_config_file_dest }}"
    owner : "{{ locales_config_file_owner }}"
    group : "{{ locales_config_file_group }}"
    mode  : "{{ locales_config_file_mode }}"


- name     : generate locale.gen configuration file
  template :
    src   : "{{ role_path }}/templates/locale.gen.j2"
    dest  : "{{ locales_gen_file_dest }}"
    owner : "{{ locales_gen_file_owner }}"
    group : "{{ locales_gen_file_group }}"
    mode  : "{{ locales_gen_file_mode }}"


- name       : generate locales
  locale_gen :
    name  : "{{ item.split(' ')[0] }}"
    state : present
  register   : locale_generated
  with_items : locales_to_configure


- name    : update system settings
  command : "{{ locales_update_command }}"
  when : locale_generated.changed == True
