---

- name: 'INSTALL | install locales package'
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: true
    cache_valid_time: '3600'
  with_items: "{{ locales_packages }}"
