---

# Tasks file for locales

- name: 'INIT | Manage variables to use for our target'
  include_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::locales'
    - 'role::locales::config'
    - 'role::locales::init'
    - 'role::locales::install'

- name: 'MAIN | install'
  include_tasks: "{{ role_path }}/tasks/install_debian.yml"
  when: ansible_os_family == "Debian"
  tags:
    - 'role::locales'
    - 'role::locales::init'
    - 'role::locales::install'


- name: 'MAIN | configure'
  include_tasks: "{{ role_path }}/tasks/configure.yml"
  tags:
    - 'role::locales'
    - 'role::locales::config'
    - 'role::locales::init'
    - 'role::locales::install'
